### PR TITLE
Enable text justification in article view

### PR DESCRIPTION
**Pull request by phloose**
With regard to better readability i thought it would be nice if the new taz app supports justified text like the old app. Therefore this pull request adds a switch to the settings and text settings fragment for altering the text justification of the webView content.

Below an example of justified and unjustified text:

taz_justified_small

The slider in the settings and text settings fragments:

taz_settings_slider

At the moment i have not written any test as i am new to Kotlin and app development. If you can give me a little hint i will add respective tests.

### CODE REVIEW

**Comment by eikectrlaltcoop** [comment]
This is a nice feature and a well-thought-and-prepared Merge Request!

I introduced your feature to the product development team. I'll let you know when they accepted this feature.

But thanks anyway for your contribution!

**Comment by l0rn** [comment]
Hello,

unfortunately the product team does not plan to officially integrate a justified text feature, therefore this PR won't be accepted into the mainline. We appreciate the effort however.

**Comment by phloose** [comment]
Hey, 

Thanks for the feedback! I personally find it much harder to read when the text is not justified since it appears kind of jagged which disturbs the visual perception. 

In anyway, keep up the good work!

**Comment by phloose** [comment]
Is there a rationale behind the fact that the iOS app DOES have text justification included and the android app not? Why is that? I really would love to have this feature...

**Comment by eikectrlaltcoop** [comment]
This is indeed incomprehensible. I will bring it up again to the product development team. I hope to give you answer here soon how we proceed :crossed_fingers:

**Comment by eikectrlaltcoop** [comment]
Just to inform you: This feature is ordered.

**Pull request closed without merging**
